CREATE TABLE tasks(
id_tasks INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
description VARCHAR(500) NOT NULL,
create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
due_date DATETIME,
is_completed BOOLEAN DEFAULT FALSE
);

SELECT * FROM tasks;

DESCRIBE tasks;